//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.15 at 12:53:15 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost/books", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost.books;
